### ISSUE TITLE
Write Vignettes

### ISSUE THREAD

**Issue by matthiasgomolka** [matthiasgomolka/sdcLog#19]
1. Getting started (gibt es einen besseren Namen?) (**??**)
1. Options in sdcLog (**Matthias**)

**Comment by Plebejer** [comment]
Ich habe einen neuen Branch für die Vignetten angelegt: https://github.com/Plebejer/sdcLog/tree/vignettes 

Falls du (@tbecker2511) auch an den Vignetten arbeitest, kannst du den gleichen branch nutzen.

**Comment by Plebejer** [comment]
Vignette zu Options geschrieben: d08ec834c6f3cac69a0786cd7e91843810c9d8e3

**Comment by Plebejer** [comment]
Beispiele:
[examples_rdsc.zip](https://github.com/Plebejer/sdcLog/files/4427525/examples_rdsc.zip)

**Comment by Plebejer** [comment]
Habe alle PR's gemerged und dann den master branch in vignettes gemerged

**Comment by tbecker2511** [comment]
Erste Version der Vignette 'Introduction to scdLog' (commit: bee3481)

**Comment by matthiasgomolka** [comment]
#43

**Comment by matthiasgomolka** [comment]
Basic vignettes done with 7ebeda5fc68b2b0985dcabc6c188f3f341f74aeb.
