### ISSUE TITLE
Add interaction term examples to Vignette

### ISSUE THREAD

**Issue by matthiasgomolka** [matthiasgomolka/sdcLog#58]
#55 was implemented in ea2f8af396650199e761efad02c53f7859865d8a.

Now it would be helpful if we would present this functionality in https://github.com/matthiasgomolka/sdcLog/blob/main/vignettes/sdcLog.Rmd.

**Discussion:**
@tbecker2511 Do you think it would be helpful to split the main vignette into distinct vignettes for each function?

**Comment by tbecker2511** [comment]
@matthiasgomolka I think for the current state it is still fine to continue with one vignette, that introduces the primary functions. Should the complexity of the functions increase further and more examples are given, then we can think about such a split

I could also have a look to present this functionality in the vignette

**Comment by tbecker2511** [comment]
@tbecker2511 create new data frame to present interaction terms and potential problems

**Comment by tbecker2511** [comment]
implementation to document the interaction term #61

**Comment by matthiasgomolka** [comment]
Merged in #62
