### ISSUE TITLE
Corrections

### ISSUE THREAD

**Issue by tbecker2511** [matthiasgomolka/sdcLog#60]
Here aspects can be collected, which still need small improvements or corrections.

- [x]  In the documentation of sdc_model the description of the argument 'data' is from sdc_descriptives, but should be adapted to sdc_model.
- [x] Something went wrong in the vignette:
    ![grafik](https://user-images.githubusercontent.com/6517388/99960325-d8bf0200-2d8c-11eb-81c6-f8a43fd1ac00.png)

**Comment by matthiasgomolka** [comment]
Fixed in de0b0c92f1e1d3107264cf7291c239daf1b7f358.
