### ISSUE TITLE
Make as.data.table() conditional

### ISSUE THREAD

**Issue by matthiasgomolka** [matthiasgomolka/sdcLog#63]
`as.data.table()` is the memory-wise most expensive operation in `sdc_descriptives()`:

![image](https://user-images.githubusercontent.com/6517388/110130373-379f0900-7dc9-11eb-8cce-85f812777475.png)

Therefore, check if `data` already is a `data.table` and skip if possible.

This applies to all `sdc_*` functions.

**Comment by matthiasgomolka** [comment]
@tbecker2511, do you want to create a Pull Request for this one?

**Comment by tbecker2511** [comment]
Sorry I didn't see this one directly! But @matthiasgomolka you can assign me such things again in the future.
